### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by tuzhao** [Jpub/AndroidStudio#1]
this book was written by you ?

**Comment by sappho192** [comment]
Hi.

This is a repository for sample codes of the book "핵심만 골라 배우는 안드로이드 스튜디오" which is published in South Korea.

Jpub is a book publisher.

**Comment by tuzhao** [comment]
okay,i got it.thanks!

**Comment by sappho192** [comment]
Would you close this issue if you've finished? Thanks!
